//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4961
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whitehole.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whitehole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # zonelist.bcsv
        ///ZoneName
        ///
        ///# scenariodata.bcsv
        ///ScenarioNo
        ///ScenarioName
        ///Comet
        ///IsHidden
        ///
        ///# names below extracted from Anarchy in the Galaxy
        ///# credit goes to Phantom Wings (or whoever found them if it isn&apos;t him)
        ///Range
        ///Distant
        ///Priority
        ///Gravity_id
        ///Gravity_type
        ///Normal
        ///Shadow
        ///Magnet
        ///Power
        ///Light
        ///Heavy
        ///Inverse
        ///type
        ///name
        ///Obj_arg0
        ///ShapeModelNo
        ///AreaShapeNo
        ///pos_x
        ///pos_y
        ///pos_z
        ///dir_x
        ///dir_y
        ///dir_z
        ///scale_x
        ///scale_y
        ///scale_z
        ///Obj_arg1
        ///Obj_arg2
        ///Obj_arg3
        ///Obj_arg4
        ///Obj_arg5
        ///Obj_arg6
        ///Obj_arg7        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string KnownFieldNames {
            get {
                return ResourceManager.GetString("KnownFieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ObjectRenderInfo {
            get {
                return ResourceManager.GetString("ObjectRenderInfo", resourceCulture);
            }
        }
    }
}
